ci:
  autoupdate_schedule: "monthly" # Like dependabot
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: false # Comment "pre-commit.ci autofix" on a PR to trigger

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-vcs-permalinks"
      - id: "check-yaml"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"

  - repo: "https://github.com/mfisher87/alexjs-pre-commit-mirror"
    rev: "v11.0.1"  # Use the sha / tag you prefer
    hooks:
    - id: "alex"

  - repo: "https://github.com/codespell-project/codespell"
    rev: "v2.2.4"
    hooks:
      - id: "codespell"
        exclude: ".codespellignore"

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v3.1.0"
    hooks:
      - id: "prettier"
        files: "CITATION.cff"
  - repo: "https://github.com/citation-file-format/cffconvert"
    rev: "054bda51dbe278b3e86f27c890e3f3ac877d616c"
    hooks:
      - id: "validate-cff"
        args:
          - "--verbose"
