# For this project, we use ReadTheDocs only for Pull Request previews. GitHub
# pages currently hosts the actual website.
version: 2


build:
  os: "ubuntu-lts-latest"

  commands:
    - "asdf plugin add pixi"
    - "asdf install pixi latest"
    - "asdf global pixi latest"

    - "pixi run render"
    - "mkdir --parents $READTHEDOCS_OUTPUT/html/"
    - "mv _build/html/* $READTHEDOCS_OUTPUT/html/."
    - "rm -rf _build"  # RTD build fails if _build/html is detected :(
