[bumpver]
current_version = "2025.5.7-1"
version_pattern = "YYYY.MM.DD[-INC0]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "v{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"CITATION.cff" = [
    'version: "{version}"$',
    'date-released: "YYYY-0M-0D"'
]
