# The ReadTheDocs preview link is "hidden" within the GitHub "Checks"
# interface. For users who don't know this, finding the preview link may be
# very difficult or frustrating. This workflow makes the link more
# findable by updating PR descriptions to include it.
name: 'Add ReadTheDocs preview link to PR description'

on:
  pull_request_target:
    types:
      - 'opened'

permissions:
  pull-requests: 'write'

jobs:
  autolink-rtd-previews:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'readthedocs/actions/preview@v1'
        with:
          project-slug: 'mfisher87'
          message-template: |
            ---
            :mag: Preview: {docs-pr-index-url}
            _Note: This Pull Request preview is provided by ReadTheDocs. Our production website, however, is currently deployed with GitHub Pages._
